name: Continuous Integration
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fish-lint:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          sudo apt-get install fish
          shopt -s globstar
          fish --no-execute **.fish
  
  markdown-lint:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md